set_property PACKAGE_PIN AD16 [get_ports dout_p]
set_property PACKAGE_PIN AF15 [get_ports sclk_p]
set_property PACKAGE_PIN AA15 [get_ports drdy_p]

set_property IOSTANDARD LVDS_25 [get_ports dout_p]
set_property IOSTANDARD LVDS_25 [get_ports sclk_p]
set_property IOSTANDARD LVDS_25 [get_ports drdy_p]
set_property DIFF_TERM TRUE [get_ports dout_p]
set_property DIFF_TERM TRUE [get_ports dout_n]
set_property DIFF_TERM TRUE [get_ports sclk_p]
set_property DIFF_TERM TRUE [get_ports sclk_n]
set_property DIFF_TERM TRUE [get_ports drdy_p]
set_property DIFF_TERM TRUE [get_ports drdy_n]

set_property PACKAGE_PIN AK13 [get_ports cs_n]
set_property PACKAGE_PIN AK12 [get_ports start]
set_property PACKAGE_PIN AH14 [get_ports dr0]
set_property PACKAGE_PIN AH13 [get_ports dr1]
set_property PACKAGE_PIN AH12 [get_ports dr2]
set_property PACKAGE_PIN AG12 [get_ports fpath]
set_property PACKAGE_PIN AF12 [get_ports ll_cfg]
set_property PACKAGE_PIN AE12 [get_ports lvds]
set_property PACKAGE_PIN AC13 [get_ports pown]
set_property PACKAGE_PIN AC14 [get_ports clk_sel]

set_property IOSTANDARD LVCMOS25 [get_ports clk_sel]
set_property IOSTANDARD LVCMOS25 [get_ports cs_n]
set_property IOSTANDARD LVCMOS25 [get_ports dr0]
set_property IOSTANDARD LVCMOS25 [get_ports dr1]
set_property IOSTANDARD LVCMOS25 [get_ports dr2]
set_property IOSTANDARD LVCMOS25 [get_ports fpath]
set_property IOSTANDARD LVCMOS25 [get_ports ll_cfg]
set_property IOSTANDARD LVCMOS25 [get_ports lvds]
set_property IOSTANDARD LVCMOS25 [get_ports pown]
set_property IOSTANDARD LVCMOS25 [get_ports start]
