set_property -dict {PACKAGE_PIN AF15 IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports SCLK_clk_p]
set_property -dict {PACKAGE_PIN AD16 IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports DOUT_v_p]
set_property -dict {PACKAGE_PIN AA15 IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports DRDY_v_p]

set_property -dict {IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports SCLK_clk_n]
set_property -dict {IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports DOUT_v_n]
set_property -dict {IOSTANDARD LVDS_25 DIFF_TERM TRUE} [get_ports DRDY_v_n]

set_property -dict {PACKAGE_PIN AK13 IOSTANDARD LVCMOS25} [get_ports cs_n]
set_property -dict {PACKAGE_PIN AK12 IOSTANDARD LVCMOS25} [get_ports start]
set_property -dict {PACKAGE_PIN AH14 IOSTANDARD LVCMOS25} [get_ports dr[0]]
set_property -dict {PACKAGE_PIN AH13 IOSTANDARD LVCMOS25} [get_ports dr[1]]
set_property -dict {PACKAGE_PIN AH12 IOSTANDARD LVCMOS25} [get_ports dr[2]]
set_property -dict {PACKAGE_PIN AG12 IOSTANDARD LVCMOS25} [get_ports fpath]
set_property -dict {PACKAGE_PIN AF12 IOSTANDARD LVCMOS25} [get_ports ll_cfg]
set_property -dict {PACKAGE_PIN AE12 IOSTANDARD LVCMOS25} [get_ports lvds]
set_property -dict {PACKAGE_PIN AC13 IOSTANDARD LVCMOS25} [get_ports pown]
set_property -dict {PACKAGE_PIN AC14 IOSTANDARD LVCMOS25} [get_ports clk_sel]
